
[package]
name = "soa_runtime"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Traits and helpers for SoA derive macro."
[lib]
name = "soa_runtime"
path = "src/lib.rs"
