[package]
name = "example_app_advanced"
version.workspace = true
edition.workspace = true

[dependencies]
soa_macros = { path = "../soa_macros" }
soa_runtime = { path = "../soa_runtime" }

[dependencies.rayon]
version = "1.8"
optional = true

[features]
default = []
parallel = ["dep:rayon"]